POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1YjNiZDZhYTA3Yzc1MGViYjBjNDVmNCIsImlhdCI6MTcwNjI3ODI2Mn0.8ejGg9KAZ2yviZ5AVs6AFO_naG0tGycwfs1PPzQKyIw

{
    "title": "Test",
    "author": "Mr. Test",
    "url": "test.test.com",
    "userId": "65b3bd6aa07c750ebb0c45f4"
}